import type { Project } from "@/content/types";

export const projects: Project[] = [
  {
    slug: "reolink",
    name: "Reolink",
    company: "Neoxi",
    role: "Senior Frontend Engineer",
    period: "2024 to present",
    domain: "Enterprise SaaS / Security",
    description:
      "Secure cloud and marketing monorepo work for Reolink spanning auth, localization, shared packages, and multi-app Next.js delivery.",
    stack: ["Next.js 15", "React 19", "TypeScript", "Ory Kratos", "Turborepo"],
    keyOutcomes: [
      "Reduced duplicated configuration by 60%",
      "Built 2 Next.js apps and 7 shared packages",
    ],
    tags: [
      "Frontend Architecture",
      "Next.js",
      "React",
      "Authentication",
      "CI/CD",
      "Infrastructure",
    ],
    caseStudySlug: "reolink-neoxi",
  },
  {
    slug: "jamloop",
    name: "Jamloop",
    company: "Neoxi",
    role: "Senior Frontend Engineer",
    period: "2024",
    domain: "Ad-tech SaaS",
    description:
      "Typed App Router platform for self-service advertising workflows, PDF reporting, observability, and release automation.",
    stack: ["Next.js", "TypeScript", "Clerk", "Storybook", "Playwright"],
    keyOutcomes: [
      "80% faster onboarding and scaffold time",
      "30% fewer production bugs",
    ],
    tags: [
      "Next.js",
      "React",
      "Design Systems",
      "Testing",
      "CI/CD",
      "Data Visualization",
    ],
    caseStudySlug: "jamloop",
  },
  {
    slug: "shop-ware",
    name: "Shop-Ware",
    role: "Frontend Engineer",
    period: "2022 to 2024",
    domain: "Automotive SaaS",
    description:
      "Legacy enterprise SaaS modernization from Backbone toward React with stronger performance, Storybook workflows, and CI discipline.",
    stack: ["React", "TypeScript", "Rails", "Storybook", "CircleCI"],
    keyOutcomes: ["40% faster page loads", "1,000+ automated tests in CI"],
    tags: [
      "React",
      "Design Systems",
      "Testing",
      "CI/CD",
      "Legacy Modernization",
    ],
    caseStudySlug: "shop-ware",
  },
  {
    slug: "mojito-mint",
    name: "Mojito Mint",
    company: "Neoxi",
    role: "Frontend Engineer",
    period: "2022",
    domain: "Web3 / Marketplace",
    description:
      "Multi-tenant management frontend with Auth0, GraphQL code generation, tenant-safe routing, and stronger release workflows.",
    stack: [
      "Next.js 12",
      "TypeScript",
      "Apollo Client",
      "Auth0",
      "Material UI",
    ],
    keyOutcomes: [
      "Zero cross-tenant routing issues",
      "70% fewer 401-related tickets",
    ],
    tags: [
      "Next.js",
      "React",
      "Authentication",
      "Full-stack",
      "Infrastructure",
    ],
    caseStudySlug: "mojito-mint",
  },
  {
    slug: "coffee",
    name: "Coffee",
    role: "Frontend Engineer",
    period: "2021 to 2022",
    domain: "Collaboration",
    description:
      "Unified collaboration product across meetings, chat, tasks, scheduling, and settings with shared UI patterns.",
    stack: ["React", "Electron", "Redux Toolkit", "React Query", "WebSockets"],
    keyOutcomes: ["20% higher engagement", "20% better reliability"],
    tags: [
      "React",
      "Design Systems",
      "Mobile",
      "Full-stack",
      "Data Visualization",
    ],
    caseStudySlug: "coffee-uniplato",
  },
  {
    slug: "satek",
    name: "Satek",
    role: "Frontend Engineer",
    period: "2020 to 2022",
    domain: "Healthcare / Desktop / Mobile",
    description:
      "Healthcare information system work across desktop and mobile with release optimization, bundle reduction, and mentorship.",
    stack: ["React", "Electron", "React Native", "Expo", "GraphQL"],
    keyOutcomes: ["4 Electron apps shipped", "40% better mobile stability"],
    tags: ["React", "Mobile", "Legacy Modernization", "Full-stack"],
    caseStudySlug: "satek",
  },
  {
    slug: "i-read",
    name: "I Read",
    role: "Full-stack Engineer",
    period: "2023 to 2024",
    domain: "Reading / Education",
    description:
      "Full-stack reading platform monorepo with a Next.js PWA, NestJS API, PostgreSQL schedules, JWT auth, audio assets, and an admin dashboard.",
    stack: ["Next.js 14", "NestJS", "PostgreSQL", "JWT", "AWS S3"],
    keyOutcomes: [
      "Reduced dependency duplication by 30%",
      "Served 6,000+ audio assets with static delivery",
    ],
    tags: ["Next.js", "Authentication", "Full-stack", "Infrastructure"],
    archive: false,
  },
  {
    slug: "green-house",
    name: "Green House",
    role: "Full-stack Engineer",
    period: "2023 to 2024",
    domain: "IoT / Data Visualization",
    description:
      "Greenhouse sensor dashboard combining React, TypeScript, Recharts, PHP endpoints, MySQL readings, and Raspberry Pi data collection.",
    stack: ["React", "TypeScript", "Recharts", "PHP", "MySQL", "Raspberry Pi"],
    keyOutcomes: [
      "Reduced aggregate fetch latency by 50%",
      "Visualized 4 greenhouse sensor metrics",
    ],
    tags: ["React", "Full-stack", "Data Visualization"],
  },
  {
    slug: "irapardaz",
    name: "IraPardaz",
    role: "Frontend Engineer",
    period: "2021",
    domain: "Business Software / Admin Panel",
    description:
      "Farsi-localized website and admin-panel monorepo using vanilla JavaScript, Tailwind CSS, Vite, Snowpack, and Yarn workspaces.",
    stack: [
      "JavaScript",
      "Tailwind CSS",
      "Vite",
      "Snowpack",
      "Yarn Workspaces",
    ],
    keyOutcomes: [
      "Reduced build times by 30%",
      "Improved RTL usability by 25%",
    ],
    tags: ["CI/CD", "Data Visualization", "Archive"],
    archive: true,
  },
  {
    slug: "dojeldi",
    name: "Dojeldi",
    role: "Team Lead",
    period: "2021",
    domain: "Reading / E-commerce",
    description:
      "Online EPUB reader, audiobook storefront, and admin panel built with Next.js, Yarn workspaces, Zustand, Material UI, and shared service modules.",
    stack: [
      "Next.js",
      "TypeScript",
      "Yarn Workspaces",
      "Zustand",
      "Material UI",
    ],
    keyOutcomes: [
      "Unified auth and error handling across 24 endpoints",
      "Reduced cross-app duplication by 30%",
    ],
    tags: ["Next.js", "React", "Full-stack", "Data Visualization"],
  },
  {
    slug: "atmosphere",
    name: "Atmosphere",
    company: "Razi University of Kermanshah",
    role: "Android Developer",
    period: "2020",
    domain: "Android Weather App",
    description:
      "Kotlin Android weather app fetching OpenWeather and OpenCage data through Retrofit with coroutines, MVVM, and offline state handling.",
    stack: ["Kotlin", "Android SDK 30", "Retrofit 2", "MVVM", "RecyclerView"],
    keyOutcomes: [
      "Reduced update errors by 40%",
      "Reduced incorrect city selections by 50%",
    ],
    tags: ["Mobile", "Archive"],
    archive: true,
  },
  {
    slug: "english-training-app-for-kids",
    name: "English training app for kids",
    company: "Razi University of Kermanshah",
    role: "Android Developer",
    period: "2020",
    domain: "Android Education App",
    description:
      "Android learning app for children with alphabet lessons, onboarding, Room storage, RecyclerView screens, and Material-style UI patterns.",
    stack: ["Android", "Java", "Kotlin", "Room", "RecyclerView"],
    keyOutcomes: [
      "Implemented onboarding and multi-activity navigation",
      "Configured AndroidX and Gradle build support",
    ],
    tags: ["Mobile", "Archive"],
    archive: true,
    links: {
      github: "https://github.com/s-mahdi/Language-Learning",
    },
  },
];
