import type { Project } from "@/content/types";

export const projects: Project[] = [
  {
    slug: "reolink",
    name: "Reolink",
    role: "Senior Frontend Engineer",
    period: "2024 to present",
    domain: "Enterprise SaaS / Security",
    description:
      "Secure cloud and marketing monorepo work spanning auth, localization, shared packages, and multi-app Next.js delivery.",
    stack: ["Next.js 15", "React 19", "TypeScript", "Ory Kratos", "Turborepo"],
    keyOutcomes: ["Reduced duplicated configuration by 60%", "Built 2 Next.js apps and 7 shared packages"],
    tags: ["Frontend Architecture", "Next.js", "React", "Authentication", "CI/CD", "Infrastructure"],
    caseStudySlug: "reolink-neoxi",
  },
  {
    slug: "jamloop",
    name: "JamLoop",
    role: "Senior Frontend Engineer",
    period: "2024",
    domain: "Ad-tech SaaS",
    description:
      "Typed App Router platform for self-service advertising workflows, PDF reporting, observability, and release automation.",
    stack: ["Next.js", "TypeScript", "Clerk", "Storybook", "Playwright"],
    keyOutcomes: ["80% faster onboarding and scaffold time", "30% fewer production bugs"],
    tags: ["Next.js", "React", "Design Systems", "Testing", "CI/CD", "Data Visualization"],
    caseStudySlug: "jamloop",
  },
  {
    slug: "shop-ware",
    name: "Shop-Ware",
    role: "Frontend Engineer",
    period: "2022 to 2024",
    domain: "Automotive SaaS",
    description:
      "Legacy enterprise SaaS modernization from Backbone toward React with stronger performance, Storybook workflows, and CI discipline.",
    stack: ["React", "TypeScript", "Rails", "Storybook", "CircleCI"],
    keyOutcomes: ["40% faster page loads", "1,000+ automated tests in CI"],
    tags: ["React", "Design Systems", "Testing", "CI/CD", "Legacy Modernization"],
    caseStudySlug: "shop-ware",
  },
  {
    slug: "mojito-mint",
    name: "Mojito Mint",
    role: "Frontend Engineer",
    period: "2022",
    domain: "Web3 / Marketplace",
    description:
      "Multi-tenant management frontend with Auth0, GraphQL code generation, tenant-safe routing, and stronger release workflows.",
    stack: ["Next.js 12", "TypeScript", "Apollo Client", "Auth0", "Material UI"],
    keyOutcomes: ["Zero cross-tenant routing issues", "70% fewer 401-related tickets"],
    tags: ["Next.js", "React", "Authentication", "Full-stack", "Infrastructure"],
    caseStudySlug: "mojito-mint",
  },
  {
    slug: "coffee",
    name: "Coffee",
    role: "Frontend Engineer",
    period: "2021 to 2022",
    domain: "Collaboration",
    description:
      "Unified collaboration product across meetings, chat, tasks, scheduling, and settings with shared UI patterns.",
    stack: ["React", "Electron", "Redux Toolkit", "React Query", "WebSockets"],
    keyOutcomes: ["20% higher engagement", "20% better reliability"],
    tags: ["React", "Design Systems", "Mobile", "Full-stack", "Data Visualization"],
    caseStudySlug: "coffee-uniplato",
  },
  {
    slug: "satek",
    name: "Satek",
    role: "Frontend Engineer",
    period: "2019 to 2021",
    domain: "Healthcare / Desktop / Mobile",
    description:
      "Healthcare information system work across desktop and mobile with release optimization, bundle reduction, and mentorship.",
    stack: ["React", "Electron", "React Native", "Expo", "GraphQL"],
    keyOutcomes: ["4 Electron apps shipped", "40% better mobile stability"],
    tags: ["React", "Mobile", "Legacy Modernization", "Full-stack"],
    caseStudySlug: "satek",
  },
  {
    slug: "i-read",
    name: "I Read",
    role: "Full-stack Engineer",
    period: "2024",
    domain: "Reading / Authentication",
    description:
      "Personal product work focused on secure auth, rate limiting, and full-stack delivery for a reader-oriented application.",
    stack: ["Next.js", "NestJS", "PostgreSQL", "JWT", "AWS S3"],
    keyOutcomes: ["Applied secure auth and storage patterns", "Used full-stack ownership to ship product slices end to end"],
    tags: ["Next.js", "Authentication", "Full-stack", "Infrastructure"],
    archive: false,
  },
  {
    slug: "green-house",
    name: "Green House",
    role: "Frontend Engineer",
    period: "2023",
    domain: "Operations / Dashboard",
    description:
      "Dashboard-focused frontend work emphasizing component reuse, structured state management, and operational clarity.",
    stack: ["React", "TypeScript", "Charting", "Storybook"],
    keyOutcomes: ["Improved dashboard coherence", "Expanded reusable UI patterns"],
    tags: ["React", "Design Systems", "Data Visualization"],
  },
  {
    slug: "irapardaz",
    name: "IraPardaz",
    role: "Frontend Engineer",
    period: "2020",
    domain: "Business Software",
    description:
      "Business application frontend work focused on stable delivery, maintainable components, and practical UI design.",
    stack: ["React", "Sass", "Redux"],
    keyOutcomes: ["Improved delivery structure", "Expanded business UI coverage"],
    tags: ["React", "Legacy Modernization", "Archive"],
    archive: true,
  },
  {
    slug: "dojeldi",
    name: "Dojeldi",
    role: "Frontend Engineer",
    period: "2023",
    domain: "Data-heavy Product",
    description:
      "Typed API integration and state management work for a data-heavy product surface with strong frontend ownership.",
    stack: ["React", "TypeScript", "REST", "GraphQL"],
    keyOutcomes: ["Improved typed integration discipline", "Supported data-rich product flows"],
    tags: ["React", "Full-stack", "Data Visualization"],
  },
  {
    slug: "infrastructure-as-code",
    name: "Infrastructure as Code",
    role: "Engineer",
    period: "2024",
    domain: "Platform / DevOps",
    description:
      "Platform-oriented work around repeatable environments, deployment workflows, and practical infrastructure automation.",
    stack: ["Terraform", "Docker", "Docker Compose", "PM2", "AWS S3"],
    keyOutcomes: ["Improved environment consistency", "Strengthened delivery automation"],
    tags: ["CI/CD", "Infrastructure", "Full-stack"],
  },
  {
    slug: "test-driven-development-and-playwright-automation",
    name: "Test-Driven Development and Playwright Automation",
    role: "Engineer",
    period: "2024",
    domain: "Testing / Automation",
    description:
      "Testing-focused work around Playwright automation, regression reduction, and disciplined frontend verification.",
    stack: ["Playwright", "Vitest", "Jest", "React Testing Library"],
    keyOutcomes: ["Expanded automated confidence", "Reduced manual verification effort"],
    tags: ["Testing", "CI/CD", "React"],
  },
  {
    slug: "atmosphere",
    name: "Atmosphere",
    role: "Frontend Engineer",
    period: "2023",
    domain: "Design-forward App",
    description:
      "Frontend work balancing expressive UI direction with maintainable component patterns and responsive behavior.",
    stack: ["Next.js", "Tailwind CSS", "Framer Motion"],
    keyOutcomes: ["Improved responsive polish", "Strengthened reusable presentation patterns"],
    tags: ["Next.js", "Design Systems", "React"],
  },
  {
    slug: "english-training-app-for-kids",
    name: "English training app for kids",
    role: "Frontend Engineer",
    period: "2019",
    domain: "Education",
    description:
      "Earlier educational product work focused on approachable interfaces, structured flows, and practical feature delivery.",
    stack: ["React", "React Native", "Expo"],
    keyOutcomes: ["Delivered kid-friendly learning flows", "Expanded mobile implementation experience"],
    tags: ["Mobile", "Archive"],
    archive: true,
  },
  {
    slug: "airport-management-algorithm",
    name: "Airport management algorithm",
    role: "Student Engineer",
    period: "University",
    domain: "Algorithms",
    description:
      "Academic project centered on algorithmic thinking and systems modeling rather than production product delivery.",
    stack: ["Algorithms", "Data Structures"],
    keyOutcomes: ["Demonstrated systems thinking", "Archive-only academic work"],
    tags: ["Archive"],
    archive: true,
  },
];
